kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployments
spec:
  replicas: 1
  selector:
    matchLables:
      name: deployment
  template:
    mwetadata:
      name: testpod1
      lables:
        name:
    spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort:80
