kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
  - name: k8scontainer
    image: humancloudak/myimage123
  restartPolicy: Never
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    name: testpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployments
spec:
  replicas: 1
  selector:
    matchLables:
      name: k8scontainer
  template:
    metadata:
      name: testpod1
      lables:
        name:
    spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 18989
---

kind: Dervice
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 18989
      targetPort: 18989
  selector:
    name: k8scontainer
  type: ClusterIP
