kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    name: k8scontainer
    image: humancloudak/poc1
    command: ["/bin/bash", "-c", "while true; do echo Hello; sleep 5; done"]
  restartPolicy: Never
